name: campfire
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}

    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
    environment:
      ADMINER_PORT: ${ADMINER_PORT}
      ADMINER_DEFAULT_DRIVER: pgsql
      ADMINER_DESIGN: nette

volumes:
  postgresql_data:
